#!/usr/bin/env python3
"""Build singleheader/simdsearch.h from include/simdsearch/.

Starts at simdsearch.h and pastes every header it includes by quoted name in
place of the #include, once each, dropping their #pragma once. System
includes are left where they are. The result is one self-contained header
with both backends, selected by the same preprocessor tests as the sources.

    python3 tools/amalgamate.py           # write singleheader/simdsearch.h
    python3 tools/amalgamate.py --check   # exit 1 if the file is out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "include" / "simdsearch"
OUT = ROOT / "singleheader" / "simdsearch.h"
ENTRY = "simdsearch.h"

INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"([^"]+)"\s*$')
PRAGMA_ONCE_RE = re.compile(r'^\s*#\s*pragma\s+once\s*$')


def amalgamate(name, seen, out):
    if name in seen:
        return
    seen.add(name)
    path = SRC / name
    out.append(f"// ---- begin {name} " + "-" * max(1, 60 - len(name)) + "\n")
    for line in path.read_text().splitlines():
        m = INCLUDE_RE.match(line)
        if m:
            amalgamate(m.group(1), seen, out)
            continue
        if PRAGMA_ONCE_RE.match(line):
            continue
        out.append(line + "\n")
    out.append(f"// ---- end {name} " + "-" * max(1, 62 - len(name)) + "\n")


def build():
    out = [
        "// simdsearch, single-header build. GENERATED by tools/amalgamate.py from\n",
        "// include/simdsearch/ -- do not edit; edit the sources and regenerate.\n",
        "//\n",
        "//   #include \"simdsearch.h\"\n",
        "//   size_t pos = simdsearch::find(haystack, needle);   // or npos\n",
        "//\n",
        "// Needs AVX-512F + AVX-512BW (compile with -mavx512f -mavx512bw) on x86-64,\n",
        "// or AArch64 NEON; C++17. See the README at github.com/lemire/simdsearch.\n",
        "#pragma once\n",
    ]
    amalgamate(ENTRY, set(), out)
    return "".join(out)


def main():
    text = build()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run python3 tools/amalgamate.py",
                  file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
